(*
 * This code was generated by the TaskGen tool from file
 *   "CommonOptionsTask.xml"
 * Version: 16.0.0.0
 * Runtime Version: v2.0.50727
 * Changes to this file may cause incorrect behavior and will be
 * overwritten when the code is regenerated.
 *)

unit CommonOptionStrs;

interface

const

	sTaskName = 'commonoptions';

	// PathsAndDefines
	sDefines = 'Defines';
	sIncludePath = 'IncludePath';
	sFinalOutputDir = 'FinalOutputDir';
	sIntermediateOutputDir = 'IntermediateOutputDir';

	// MiscInternalOptions
	sShowGeneralMessages = 'ShowGeneralMessages';

	// CommonPackageOpts
	sPackageImports = 'PackageImports';
	sAllPackageLibs = 'AllPackageLibs';
	sPackageLibs = 'PackageLibs';
	sDesignOnlyPackage = 'DesignOnlyPackage';
	sRuntimeOnlyPackage = 'RuntimeOnlyPackage';

	// DelphiInternalOptions
	sGenPackage = 'GenPackage';
	sGenDll = 'GenDll';
	sUsePackages = 'UsePackages';
	sHasTypeLib = 'HasTypeLib';
	sAutoGenImportAssembly = 'AutoGenImportAssembly';
	sAutoRegisterTLB = 'AutoRegisterTLB';
	sImageDebugInfo = 'ImageDebugInfo';
	sDebugSourcePath = 'DebugSourcePath';

	// OutputFilenameModifiers
	sOutputExt = 'OutputExt';
	sOutputName = 'OutputName';
	sDllPrefixDefined = 'DllPrefixDefined';
	sDllPrefix = 'DllPrefix';
	sDllVersion = 'DllVersion';
	sDllSuffix = 'DllSuffix';

	// C++InternalOptions
	sMultithreaded = 'Multithreaded';
	sDynamicRTL = 'DynamicRTL';
	sUsingDelphiRTL = 'UsingDelphiRTL';
	sLinkCodeGuard = 'LinkCodeGuard';
	sRunBCCOutOfProcess = 'RunBCCOutOfProcess';

	// WindowsVersionInformation
	sVerInfo_IncludeVerInfo = 'VerInfo_IncludeVerInfo';
	sVerInfo_MajorVer = 'VerInfo_MajorVer';
	sVerInfo_MinorVer = 'VerInfo_MinorVer';
	sVerInfo_Release = 'VerInfo_Release';
	sVerInfo_Build = 'VerInfo_Build';
	sVerInfo_Debug = 'VerInfo_Debug';
	sVerInfo_PreRelease = 'VerInfo_PreRelease';
	sVerInfo_Special = 'VerInfo_Special';
	sVerInfo_Private = 'VerInfo_Private';
	sVerInfo_DLL = 'VerInfo_DLL';
	sVerInfo_Locale = 'VerInfo_Locale';
	sVerInfo_CodePage = 'VerInfo_CodePage';
	sVerInfo_CompanyName = 'VerInfo_CompanyName';
	sVerInfo_FileDescription = 'VerInfo_FileDescription';
	sVerInfo_FileVersion = 'VerInfo_FileVersion';
	sVerInfo_InternalName = 'VerInfo_InternalName';
	sVerInfo_LegalCopyright = 'VerInfo_LegalCopyright';
	sVerInfo_LegalTrademarks = 'VerInfo_LegalTrademarks';
	sVerInfo_OriginalFilename = 'VerInfo_OriginalFilename';
	sVerInfo_ProductName = 'VerInfo_ProductName';
	sVerInfo_ProductVersion = 'VerInfo_ProductVersion';
	sVerInfo_Comments = 'VerInfo_Comments';
	sVerInfo_Keys = 'VerInfo_Keys';
	sVerInfo_AutoGenVersion = 'VerInfo_AutoGenVersion';
	sIcon_MainIcon = 'Icon_MainIcon';
	sManifest_File = 'Manifest_File';
	sVCL_Custom_Styles = 'VCL_Custom_Styles';

	// DebuggerProjectOptions
	sDebugger_RunParams = 'Debugger_RunParams';
	sDebugger_RemoteRunParams = 'Debugger_RemoteRunParams';
	sDebugger_HostApplication = 'Debugger_HostApplication';
	sDebugger_RemotePath = 'Debugger_RemotePath';
	sDebugger_RemoteHost = 'Debugger_RemoteHost';
	sDebugger_EnvVars = 'Debugger_EnvVars';
	sDebugger_SymTabs = 'Debugger_SymTabs';
	sDebugger_Launcher = 'Debugger_Launcher';
	sDebugger_RemoteLauncher = 'Debugger_RemoteLauncher';
	sDebugger_IncludeSystemVars = 'Debugger_IncludeSystemVars';
	sDebugger_UseLauncher = 'Debugger_UseLauncher';
	sDebugger_UseRemoteLauncher = 'Debugger_UseRemoteLauncher';
	sDebugger_CWD = 'Debugger_CWD';
	sDebugger_RemoteCWD = 'Debugger_RemoteCWD';
	sDebugger_RemoteDebug = 'Debugger_RemoteDebug';
	sDebugger_DebugSourcePath = 'Debugger_DebugSourcePath';
	sDebugger_LoadAllSymbols = 'Debugger_LoadAllSymbols';
	sDebugger_LoadUnspecifiedSymbols = 'Debugger_LoadUnspecifiedSymbols';
	sDebugger_SymbolSourcePath = 'Debugger_SymbolSourcePath';

	// BuildEvents
	sPreBuildEvent = 'PreBuildEvent';
	sPreBuildEventCancelOnError = 'PreBuildEventCancelOnError';
	sPreLinkEvent = 'PreLinkEvent';
	sPreLinkEventCancelOnError = 'PreLinkEventCancelOnError';
	sPostBuildEvent = 'PostBuildEvent';
	sPostBuildEventExecuteWhen = 'PostBuildEventExecuteWhen';
		sPostBuildEventExecuteWhen_Always = 'Always';
		sPostBuildEventExecuteWhen_TargetOutOfDate = 'TargetOutOfDate';
	sPostBuildEventCancelOnError = 'PostBuildEventCancelOnError';

implementation

end.
