(*
 * Copyright(c) 2022 Embarcadero Technologies, Inc.
 *
 * This code was generated by the TaskGen tool from file
 *   "CPPCOMMONTask.xml"
 * Version: 28.0.0.0
 * Runtime Version: v4.0.30319
 * Changes to this file may cause incorrect behavior and will be
 * overwritten when the code is regenerated.
 *)

unit CPPCOMMONStrs;

interface

const

	sTaskName = 'cppcommon';

	// C++DirectoriesAndConditionals
	sBPILibOutputDir = 'BPILibOutputDir';
	s_TCHARMapping = '_TCHARMapping';
		s_TCHARMapping_char = 'char';
		s_TCHARMapping_wchar_t = 'wchar_t';

implementation

end.
