(*
 * Copyright(c) 2022 Embarcadero Technologies, Inc.
 *
 * This code was generated by the TaskGen tool from file
 *   "TLIBTask.xml"
 * Version: 28.0.0.0
 * Runtime Version: v4.0.30319
 * Changes to this file may cause incorrect behavior and will be
 * overwritten when the code is regenerated.
 *)

unit TLIBStrs;

interface

const

	sTaskName = 'tlib';

	// TLIBOptions
	sListingFileName = 'TLIB_ListingFileName';
	sCaseSensitive = 'TLIB_CaseSensitive';
	sPageSize = 'TLIB_PageSize';
	sPurgeCommentRecords = 'TLIB_PurgeCommentRecords';
	// Outputs
	sOutput_OutputFile = 'OutputFile';

implementation

end.
