{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 2010-2022 Embarcadero Technologies, Inc. }
{              All rights reserved                      }
{                                                       }
{*******************************************************}

{ OSTypes.h }
type
  wide = Int64;
  UnsignedWide = UInt64;
  {$EXTERNALSYM UnsignedWide}
