{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 2010-2011 Embarcadero Technologies, Inc. }
{                                                       }
{*******************************************************}

function UpTime; external CarbonCoreLib name '_UpTime';
function AbsoluteDeltaToDuration; external CarbonCoreLib name '_AbsoluteDeltaToDuration';
function AbsoluteDeltaToNanoseconds; external CarbonCoreLib name '_AbsoluteDeltaToNanoseconds';
function AbsoluteToDuration; external CarbonCoreLib name '_AbsoluteToDuration';
function AbsoluteToNanoseconds; external CarbonCoreLib name '_AbsoluteToNanoseconds';
function AddAbsoluteToAbsolute; external CarbonCoreLib name '_AddAbsoluteToAbsolute';
function AddDurationToAbsolute; external CarbonCoreLib name '_AddDurationToAbsolute';
function AddNanosecondsToAbsolute; external CarbonCoreLib name '_AddNanosecondsToAbsolute';
function DurationToAbsolute; external CarbonCoreLib name '_DurationToAbsolute';
function DurationToNanoseconds; external CarbonCoreLib name '_DurationToNanoseconds';
function NanosecondsToAbsolute; external CarbonCoreLib name '_NanosecondsToAbsolute';
function NanosecondsToDuration; external CarbonCoreLib name '_NanosecondsToDuration';
function SubAbsoluteFromAbsolute; external CarbonCoreLib name '_SubAbsoluteFromAbsolute';
function SubDurationFromAbsolute; external CarbonCoreLib name '_SubDurationFromAbsolute';
function SubNanosecondsFromAbsolute; external CarbonCoreLib name '_SubNanosecondsFromAbsolute';
