{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 1995-2022 Embarcadero Technologies, Inc. }
{              All rights reserved                      }
{                                                       }
{*******************************************************}

const
//TODO -otgerdes -cTranslate: Header translation of limits.h

{from linux/limits.h}
  PATH_MAX    =  4096; // # chars in a path name including nul 
  {$EXTERNALSYM PATH_MAX}


