{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 1995-2011 Embarcadero Technologies, Inc. }
{                                                       }
{*******************************************************}

const
  TCP_NODELAY = $01;
  {$EXTERNALSYM TCP_NODELAY}

