
//---------------------------------------------------------------------------

// This software is Copyright (c) 2011 Embarcadero Technologies, Inc. 
// You may only use this software if you are an authorized licensee
// of Delphi, C++Builder or RAD Studio (Embarcadero Products).
// This software is considered a Redistributable as defined under
// the software license agreement that comes with the Embarcadero Products
// and is subject to that software license agreement.

//---------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 4.0.22.733
//     Runtime Version: 4.0.30319.1
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE CW3}
{$HIDE PW12}

namespace DelphiPrismWebApp;

interface

type
    Logoff = public partial class
    protected 
        var Head1: System.Web.UI.HtmlControls.HtmlHead;
        var Form1: System.Web.UI.HtmlControls.HtmlForm;
end;

implementation

end.
